### ISSUE TITLE
Notebook request for proteins with no native ligands

### ISSUE THREAD

**Issue by arya-blip** [RyanZR/ColabDock-Vina#3]
Hi Ryan. Awesome notebooks you got there. 

Would like to know if there is also an available for proteins with no native ligands?

Thanks.

**Comment by RyanZR** [comment]
Hi Arya. Thanks for checking out the notebooks! Glad that you're finding them awesome!

As for the docking notebooks for protein with no native ligands, I excited to share that I am working on implementing this as a new feature in the upcoming update. You can access them in the [develop branch](https://github.com/RyanZR/labodock/tree/develop). Keep in mind, they might have a few kinks to iron out as they are not stable and still in the experimental phase. Feel free to explore them!

Regards.

**Comment by arya-blip** [comment]
Thank you so much @RyanZR

**Comment by RyanZR** [comment]
Hi Arya, this feature is now available in LABODOCK v2.0.0 release.
