### ISSUE TITLE
mk_prepare_ligand.py causes ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by italobale** [RyanZR/ColabDock-Vina#5]
In the 'virtual_screening.ipynb' in the step 'Parameterise ligands with Gasteiger charges'
the following command 
``        !mk_prepare_ligand.py -i {LIG_sdf_lFile} -o {LIG_pdbqt_dFFile}
``

causes this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/mk_prepare_ligand.py", line 14, in <module>
    from meeko import MoleculePreparation
  File "/usr/local/lib/python3.10/site-packages/meeko/__init__.py", line 36, in <module>
    from . import analysis
  File "/usr/local/lib/python3.10/site-packages/meeko/analysis/__init__.py", line 7, in <module>
    from .fingerprint_interactions import FingerprintInteractions
  File "/usr/local/lib/python3.10/site-packages/meeko/analysis/fingerprint_interactions.py", line 10, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by RyanZR** [comment]
Hi @italobale, I couldn't reproduce this error in Google Colab. Can you please specify the platform used to run the notebooks?

Meanwhile, you can attempt to resolve the issue by installing additional packages with the following code. It seems the issue might be related to running the notebook on platforms other than Google Colab, which currently is not supported. 

```bash
!mamba install -c anaconda -c conda-forge pandas=1.5.3 matplotlib=3.7.1 seaborn=0.12.2
```

**Comment by italobale** [comment]
@RyanZR 
Thanks for checking this.

When I had the issue I was running the notebook on Google Colab.

However, I tried again running the notebook on Colab, and this seems to work now.
There might have been an issue in my Colab Runtime session, which corrupted somehow the installation.

**Comment by RyanZR** [comment]
@italobale
Thanks for the update. It's great to hear that the issue resolved itself. 
If you encounter this issue again, feel free to reopen the issue again.
