### ISSUE TITLE
Issue with ligand preparation

### ISSUE THREAD

**Issue by avl911** [RyanZR/ColabDock-Vina#6]
Hi Ryan. 
First of all, what a delightful piece of work you got here! It's so didactic that I'm planning to use it with my students.
Unfortunately, after a careful reading of your instructions, I am unable to move forward beyond 04 preparing the ligand step, despite I separetely ran the first cell of software installation. However,  the issue is particular to the Parameterise ligand with Gasteiger charges, where the pdbqt cannot be found, hence, no docking calculation can be performed.
I attach the error:
"
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-40-952cb4f514e4>](https://8m9a1e6xo1r-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231114-060201_RC00_582258937#) in <cell line: 19>()
     17 os.makedirs(LIG_dFLD, exist_ok=True)
     18 get_ipython().system('mk_prepare_ligand.py -i {LIG_sdf_lFile} -o {LIG_pdbqt_dFFile} > /dev/null 2>&1')
---> 19 pdbqt_add_chid(LIG_pdbqt_dFFile)
     20 
     21 print(f'+ Parameterisation: {LIG_sdf} > {LIG_pdbqt}')

[<ipython-input-40-952cb4f514e4>](https://8m9a1e6xo1r-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231114-060201_RC00_582258937#) in pdbqt_add_chid(inpt_file)
      5 
      6 def pdbqt_add_chid(inpt_file: str) -> None:
----> 7     with open(inpt_file, 'r') as inpt:
      8         data = inpt.read()
      9     new_data = data.replace('  UNL  ', '  UNL A')

FileNotFoundError: [Errno 2] No such file or directory: '/content/7KBS_/DOCKING/RLXF/RLXF.pdbqt' 
"

I hope you can help me.
Again, such a great work and thanks for sharing,

Abe

**Comment by RyanZR** [comment]
Hi @avl911,

I appreciate your positive feedback and glad you are considering using the material with your students.

I have found a bug that leads to the error and it is related to the installation step. Specifically, if the `Install packages and dependencies` cell is executed **more than once** *(eg: running the installation cell followed by using the `Run all` option as the instruction suggested)*, `meeko` package *(to use `mk_prepare_ligand.py`)* may not be imported correctly as there is a silent package update *(`pillow 9.4.0` -> `10.1.0`)* through `pip` at the second installation run that seems to causes the issue. 

However, running the installation cell **only once** *(without subsequent re-run of that particular cell after the session auto-restart)* should resolve this issue. 

I am actively working on a fix, which will be included in the upcoming minor update. You can access the latest developments in the [develop branch](https://github.com/RyanZR/labodock/tree/develop). Keep in mind that the notebooks are still experimental. Feel free to reach out for further clarification.

Ryan

**Comment by avl911** [comment]
Dear Ryan,
Thank you for your kind reply. I'll keep trying with your instructions in order to avoid another mess up hoho.
Abe
